"""
ITBIS - Day 18 ML Anomaly Detection

This module trains and scores an Isolation Forest model using
the employee-per-day feature table generated by ml_features.py.
"""

from __future__ import annotations

from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import IsolationForest

from .ml_features import FEATURE_COLUMNS


# ---------------------------------------------------------
# Model configuration
# ---------------------------------------------------------

MODEL_PATH = Path(__file__).resolve().parent.parent / "models" / "anomaly_model.pkl"

DEFAULT_CONTAMINATION = 0.05
N_ESTIMATORS = 100
RANDOM_STATE = 42


def train_anomaly_model(
    features: pd.DataFrame,
    contamination: float = DEFAULT_CONTAMINATION,
) -> IsolationForest:
    """
    Train and save an Isolation Forest model.

    Args:
        features: Employee-per-day feature table.
        contamination: Expected proportion of anomalies.

    Returns:
        Trained IsolationForest model.
    """

    if features.empty:
        raise ValueError("Feature table is empty. Cannot train the model.")

    missing_columns = [
        column
        for column in FEATURE_COLUMNS
        if column not in features.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required feature columns: {missing_columns}"
        )

    X = features[FEATURE_COLUMNS]

    # Make sure the model receives only numeric values.
    if X.isna().any().any():
        raise ValueError(
            "Feature table contains NaN values. "
            "Clean the feature table before training."
        )

    model = IsolationForest(
        n_estimators=N_ESTIMATORS,
        contamination=contamination,
        random_state=RANDOM_STATE,
    )

    model.fit(X)

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)

    joblib.dump(model, MODEL_PATH)

    return model


def load_anomaly_model() -> IsolationForest:
    """
    Load the previously trained Isolation Forest model.

    Returns:
        Trained IsolationForest model.
    """

    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Trained anomaly model not found at: {MODEL_PATH}"
        )

    return joblib.load(MODEL_PATH)


def score_anomalies(
    model: IsolationForest,
    features: pd.DataFrame,
) -> pd.DataFrame:
    """
    Score employee-day feature rows using the trained model.

    Adds:
        anomaly_score:
            Continuous anomaly score. More negative means
            more anomalous.

        is_anomaly:
            True when Isolation Forest classifies the row
            as an anomaly.
    """

    if features.empty:
        return features.copy()

    missing_columns = [
        column
        for column in FEATURE_COLUMNS
        if column not in features.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required feature columns: {missing_columns}"
        )

    X = features[FEATURE_COLUMNS]

    if X.isna().any().any():
        raise ValueError(
            "Feature table contains NaN values. "
            "Clean the feature table before scoring."
        )

    scored = features.copy()

    scored["anomaly_score"] = model.decision_function(X)

    scored["is_anomaly"] = model.predict(X) == -1

    return scored.sort_values(
        "anomaly_score",
        ascending=True,
    ).reset_index(drop=True)